name: Build and Push Docker Image

on:
  push:
    branches: [release] # Trigger the workflow on push to the release branch
    tags: ["v*"] # Trigger the workflow on push of tags starting with 'v'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.9.0"

      - name: Create .env.local for frontend
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" > apps/web/.env.local
          echo "VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}" >> apps/web/.env.local

      - name: Install dependencies and build frontend
        run: |
          cd apps/web
          npm install
          npm run build

      - name: Copy frontend build to backend
        run: |
          mkdir -p apps/api/public
          cp -r apps/web/dist apps/api/public

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./apps/api
          push: true
          tags: ghcr.io/${{ github.repository }}/saase:latest
